Created by Will Hsu
7/13/2022

In [11]:
# importing libraries
import pandas as pd # data science essentials
import matplotlib.pyplot as plt # essential graphical output
import seaborn as sns # enhanced graphical output

df = pd.read_csv("credit_risk_training.csv")
df.head(15)

,CheckingStatus,LoanDuration,CreditHistory,LoanPurpose,LoanAmount,ExistingSavings,EmploymentDuration,InstallmentPercent,Sex,OthersOnLoan,...,OwnsProperty,Age,InstallmentPlans,Housing,ExistingCreditsCount,Job,Dependents,Telephone,ForeignWorker,Risk
0,0_to_200,31,credits_paid_to_date,other,1889,100_to_500,less_1,3,female,none,...,savings_insurance,32,none,own,1,skilled,1,none,yes,No Risk
1,less_0,18,credits_paid_to_date,car_new,462,less_100,1_to_4,2,female,none,...,savings_insurance,37,stores,own,2,skilled,1,none,yes,No Risk
2,less_0,15,prior_payments_delayed,furniture,250,less_100,1_to_4,2,male,none,...,real_estate,28,none,own,2,skilled,1,yes,no,No Risk
3,0_to_200,28,credits_paid_to_date,retraining,3693,less_100,greater_7,3,male,none,...,savings_insurance,32,none,own,1,skilled,1,none,yes,No Risk
4,no_checking,28,prior_payments_delayed,education,6235,500_to_1000,greater_7,3,male,none,...,unknown,57,none,own,2,skilled,1,none,yes,Risk
5,no_checking,32,outstanding_credit,vacation,9604,500_to_1000,greater_7,6,male,co-applicant,...,unknown,57,none,free,2,skilled,2,yes,yes,Risk
6,no_checking,9,prior_payments_delayed,car_new,1032,100_to_500,4_to_7,3,male,none,...,savings_insurance,41,none,own,1,management_self-employed,1,none,yes,No Risk
7,less_0,16,credits_paid_to_date,vacation,3109,less_100,4_to_7,3,female,none,...,car_other,36,none,own,2,skilled,1,none,yes,No Risk
8,0_to_200,11,credits_paid_to_date,car_new,4553,less_100,less_1,3,female,none,...,savings_insurance,22,none,own,1,management_self-employed,1,none,yes,No Risk
9,no_checking,35,outstanding_credit,appliances,7138,500_to_1000,greater_7,5,male,co-applicant,...,unknown,49,none,free,2,skilled,2,yes,yes,Risk
10,less_0,5,all_credits_paid_back,car_new,1523,less_100,unemployed,2,female,none,...,real_estate,19,none,rent,1,management_self-employed,1,none,yes,No Risk
11,less_0,9,all_credits_paid_back,car_used,4302,less_100,1_to_4,3,male,none,...,car_other,34,none,free,1,skilled,1,none,yes,No Risk
12,no_checking,27,outstanding_credit,furniture,3310,500_to_1000,greater_7,5,male,none,...,car_other,40,none,free,1,skilled,1,yes,yes,No Risk
13,0_to_200,29,credits_paid_to_date,furniture,3705,less_100,less_1,3,female,co-applicant,...,car_other,44,none,own,1,skilled,1,none,yes,No Risk
14,greater_200,4,all_credits_paid_back,car_new,2407,less_100,1_to_4,3,female,none,...,car_other,52,none,own,1,skilled,2,yes,yes,No Risk

In [12]:
#use map to fix
d = {'no_checking': '0', 'less_0': '10' ,'0_to_200': '100', 'greater_200': '200'}
df["CheckingStatus"] = df["CheckingStatus"].map(d)
df[['CheckingStatus']] = df[['CheckingStatus']].apply(pd.to_numeric)
# fix telephone and risk
d1 = {'none':'0', 'yes':'1'}
d2 = {'No Risk':'0', 'Risk':'1'}
df["Telephone"] = df["Telephone"].map(d1)
df["Risk"] = df["Risk"].map(d2)

df[['Telephone', 'Risk']] = df[['Telephone','Risk']].apply(pd.to_numeric)

# EmploymentDuration
d3 = {'unemployed':'0', 'less_1':'1', '1_to_4':'2.5', '4_to_7': '5.5', 'greater_7':'10'}
df["EmploymentDuration"] = df["EmploymentDuration"].map(d3)
#sex
d4 = {'female':'0', 'male':"1"}
df["Sex"] = df["Sex"].map(d4)

df[['EmploymentDuration', "Sex"]] = df[['EmploymentDuration','Sex']].apply(pd.to_numeric)

### housing 
d5 = {"free":'1', 'own':'1', 'rent':'0'}
df["Housing"] = df["Housing"].map(d5)
###OthersOnLoan
d6 = {"none":"0", "co-applicant":"1", "guarantor":"2"}
df["OthersOnLoan"] = df["OthersOnLoan"].map(d6)

df[['Housing', "OthersOnLoan"]] = df[['Housing','OthersOnLoan']].apply(pd.to_numeric)

## ExistingSavings
d7 = {'unknown':'0' , 'less_100':'100', '100_to_500':'300', '500_to_1000':'750', 'greater_1000':'1000'}
df["ExistingSavings"] = df["ExistingSavings"].map(d7)
df[["ExistingSavings"]] = df[['ExistingSavings']].apply(pd.to_numeric)


df.head(20)

,CheckingStatus,LoanDuration,CreditHistory,LoanPurpose,LoanAmount,ExistingSavings,EmploymentDuration,InstallmentPercent,Sex,OthersOnLoan,...,OwnsProperty,Age,InstallmentPlans,Housing,ExistingCreditsCount,Job,Dependents,Telephone,ForeignWorker,Risk
0,100,31,credits_paid_to_date,other,1889,300,1.0,3,0,0,...,savings_insurance,32,none,1,1,skilled,1,0,yes,0
1,10,18,credits_paid_to_date,car_new,462,100,2.5,2,0,0,...,savings_insurance,37,stores,1,2,skilled,1,0,yes,0
2,10,15,prior_payments_delayed,furniture,250,100,2.5,2,1,0,...,real_estate,28,none,1,2,skilled,1,1,no,0
3,100,28,credits_paid_to_date,retraining,3693,100,10.0,3,1,0,...,savings_insurance,32,none,1,1,skilled,1,0,yes,0
4,0,28,prior_payments_delayed,education,6235,750,10.0,3,1,0,...,unknown,57,none,1,2,skilled,1,0,yes,1
5,0,32,outstanding_credit,vacation,9604,750,10.0,6,1,1,...,unknown,57,none,1,2,skilled,2,1,yes,1
6,0,9,prior_payments_delayed,car_new,1032,300,5.5,3,1,0,...,savings_insurance,41,none,1,1,management_self-employed,1,0,yes,0
7,10,16,credits_paid_to_date,vacation,3109,100,5.5,3,0,0,...,car_other,36,none,1,2,skilled,1,0,yes,0
8,100,11,credits_paid_to_date,car_new,4553,100,1.0,3,0,0,...,savings_insurance,22,none,1,1,management_self-employed,1,0,yes,0
9,0,35,outstanding_credit,appliances,7138,750,10.0,5,1,1,...,unknown,49,none,1,2,skilled,2,1,yes,1
10,10,5,all_credits_paid_back,car_new,1523,100,0.0,2,0,0,...,real_estate,19,none,0,1,management_self-employed,1,0,yes,0
11,10,9,all_credits_paid_back,car_used,4302,100,2.5,3,1,0,...,car_other,34,none,1,1,skilled,1,0,yes,0
12,0,27,outstanding_credit,furniture,3310,750,10.0,5,1,0,...,car_other,40,none,1,1,skilled,1,1,yes,0
13,100,29,credits_paid_to_date,furniture,3705,100,1.0,3,0,1,...,car_other,44,none,1,1,skilled,1,0,yes,0
14,200,4,all_credits_paid_back,car_new,2407,100,2.5,3,0,0,...,car_other,52,none,1,1,skilled,2,1,yes,0
15,0,33,all_credits_paid_back,furniture,3810,300,1.0,2,0,1,...,savings_insurance,35,none,1,1,skilled,1,0,yes,1
16,100,4,all_credits_paid_back,car_new,250,100,2.5,2,0,0,...,real_estate,26,none,1,1,skilled,1,0,yes,0
17,0,39,prior_payments_delayed,repairs,7150,750,5.5,3,1,1,...,unknown,52,none,1,2,skilled,1,1,yes,1
18,100,4,all_credits_paid_back,car_new,250,100,2.5,2,0,0,...,real_estate,28,none,1,1,skilled,1,0,yes,0
19,10,13,all_credits_paid_back,vacation,2317,100,1.0,2,0,0,...,savings_insurance,27,stores,1,2,skilled,1,0,yes,0

In [13]:
df.to_excel("risk_fixed.xlsx")

In [27]:
df.corr(method='pearson')

,CheckingStatus,LoanDuration,LoanAmount,ExistingSavings,EmploymentDuration,InstallmentPercent,Sex,OthersOnLoan,CurrentResidenceDuration,Age,Housing,ExistingCreditsCount,Dependents,Telephone,Risk
CheckingStatus,1.000000,-0.120616,-0.152160,-0.068282,-0.095771,-0.139366,-0.072334,-0.118868,-0.125607,-0.132434,0.021534,-0.106566,-0.112530,-0.092534,-0.098319
LoanDuration,-0.120616,1.000000,0.670614,0.379179,0.556379,0.687898,0.346548,0.342515,0.557946,0.546914,0.391205,0.489787,0.293867,0.413876,0.442021
LoanAmount,-0.152160,0.670614,1.000000,0.304577,0.497196,0.722800,0.346753,0.360616,0.614925,0.641352,0.425250,0.562614,0.338788,0.431865,0.450247
ExistingSavings,-0.068282,0.379179,0.304577,1.000000,0.314802,0.345450,0.247349,0.177836,0.315632,0.310828,0.164915,0.259609,0.108924,0.235721,0.233842
EmploymentDuration,-0.095771,0.556379,0.497196,0.314802,1.000000,0.671958,0.339917,0.315293,0.470940,0.577201,0.353294,0.453664,0.276899,0.391640,0.460445
InstallmentPercent,-0.139366,0.687898,0.722800,0.345450,0.671958,1.000000,0.360339,0.321851,0.657493,0.617009,0.442934,0.516673,0.324706,0.436393,0.415928
Sex,-0.072334,0.346548,0.346753,0.247349,0.339917,0.360339,1.000000,0.151290,0.372995,0.284252,0.194583,0.281388,0.177739,0.301323,0.255424
OthersOnLoan,-0.118868,0.342515,0.360616,0.177836,0.315293,0.321851,0.151290,1.000000,0.314262,0.421958,0.193734,0.233593,0.168936,0.349602,0.316857
CurrentResidenceDuration,-0.125607,0.557946,0.614925,0.315632,0.470940,0.657493,0.372995,0.314262,1.000000,0.542147,0.346492,0.420342,0.283789,0.414245,0.425533
Age,-0.132434,0.546914,0.641352,0.310828,0.577201,0.617009,0.284252,0.421958,0.542147,1.000000,0.420740,0.536857,0.316068,0.506777,0.461028
Housing,0.021534,0.391205,0.425250,0.164915,0.353294,0.442934,0.194583,0.193734,0.346492,0.420740,1.000000,0.314868,0.145466,0.323436,0.245427
ExistingCreditsCount,-0.106566,0.489787,0.562614,0.259609,0.453664,0.516673,0.281388,0.233593,0.420342,0.536857,0.314868,1.000000,0.335467,0.403899,0.396117
Dependents,-0.112530,0.293867,0.338788,0.108924,0.276899,0.324706,0.177739,0.168936,0.283789,0.316068,0.145466,0.335467,1.000000,0.355162,0.229990
Telephone,-0.092534,0.413876,0.431865,0.235721,0.391640,0.436393,0.301323,0.349602,0.414245,0.506777,0.323436,0.403899,0.355162,1.000000,0.354378
Risk,-0.098319,0.442021,0.450247,0.233842,0.460445,0.415928,0.255424,0.316857,0.425533,0.461028,0.245427,0.396117,0.229990,0.354378,1.000000

In [14]:
X = df[['CheckingStatus', 'LoanDuration', 'LoanAmount', 'ExistingSavings', 'EmploymentDuration', 'InstallmentPercent',
        'Sex', 'OthersOnLoan', 'Age', 'Housing','ExistingCreditsCount', 'Dependents','Telephone']]
y = df['Risk']

In [15]:
from sklearn import linear_model

regr = linear_model.LinearRegression()
regr.fit(X, y)

LinearRegression()

In [25]:
#'CheckingStatus' :100, 'LoanDuration' 20, 'LoanAmount' 3693, 'EmploymentDuration' 5.5, 'InstallmentPercent' 3,
#'Sex' 0, 'OthersOnLoan' 1, 'Age' 41, 'Housing' 0,'ExistingCreditsCount' 2, 'Dependents' 1,'Telephone' 1
predictedRisk = regr.predict([[100, 20, 3000, 600 ,5.5, 3, 0, 1, 41, 0, 2, 1, 1]])
print(predictedRisk)

[0.52635239]

C:\Users\gostj\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

the model shows this costumer has 0.53988 Risk percentage.

In [19]:
print(regr.coef_.round(4))

[-0.0001  0.005   0.      0.      0.032  -0.0418  0.0345  0.0976  0.0049
 -0.0196  0.0791  0.0119  0.0633]